//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2._uc.dashboard
{

    public partial class uc_userLoginChart
    {

        protected global::System.Web.UI.WebControls.Panel ChartContainer;

        protected global::System.Web.UI.WebControls.Literal litChartScript;
    }
}
