//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2.backstage.care
{

    public partial class edit
    {

        protected global::System.Web.UI.WebControls.Literal Literal_pathAction;

        protected global::System.Web.UI.WebControls.Literal Literal_title;

        protected global::System.Web.UI.WebControls.HiddenField HiddenField_treeId;

        protected global::System.Web.UI.WebControls.HiddenField HiddenField_careId;

        protected global::System.Web.UI.WebControls.Label Label_systemTreeNo;

        protected global::System.Web.UI.WebControls.Label Label_speciesName;

        protected global::System.Web.UI.WebControls.Label Label_cityName;

        protected global::System.Web.UI.WebControls.Label Label_areaName;

        protected global::System.Web.UI.WebControls.Label Label_manager;

        protected global::System.Web.UI.WebControls.Label Label_recordStatus;

        protected global::System.Web.UI.WebControls.TextBox TextBox_careDate;

        protected global::System.Web.UI.WebControls.TextBox TextBox_recorder;

        protected global::System.Web.UI.WebControls.TextBox TextBox_reviewer;

        protected global::System.Web.UI.WebControls.Button Button_save;

        protected global::System.Web.UI.WebControls.Button Button_temp;

        protected global::System.Web.UI.WebControls.Button Button_delete;

        protected global::System.Web.UI.WebControls.Button Button_cancel;
    }
}
