//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2.backstage.dashboard
{

    public partial class sm
    {

        protected global::System.Web.UI.WebControls.Literal litPendingAccounts;

        protected global::System.Web.UI.WebControls.Literal litPendingApprovedLastMonth;

        protected global::System.Web.UI.WebControls.Literal litPendingApprovedCurrentMonth;

        protected global::System.Web.UI.WebControls.Literal litTreeRecordTotal;

        protected global::System.Web.UI.WebControls.Literal litTreeRecordLastMonth;

        protected global::System.Web.UI.WebControls.Literal litTreeRecordCurrentMonth;

        protected global::System.Web.UI.WebControls.Literal litHealthRecordTotal;

        protected global::System.Web.UI.WebControls.Literal litHealthRecordLastMonth;

        protected global::System.Web.UI.WebControls.Literal litHealthRecordCurrentMonth;

        protected global::System.Web.UI.WebControls.Literal litPatrolRecordTotal;

        protected global::System.Web.UI.WebControls.Literal litPatrolRecordLastMonth;

        protected global::System.Web.UI.WebControls.Literal litPatrolRecordCurrentMonth;

        protected global::System.Web.UI.WebControls.Literal litCareRecordTotal;

        protected global::System.Web.UI.WebControls.Literal litCareRecordLastMonth;

        protected global::System.Web.UI.WebControls.Literal litCareRecordCurrentMonth;

        protected global::System.Web.UI.WebControls.Literal litTreeStatusAnnounced;

        protected global::System.Web.UI.WebControls.Literal litTreeStatusQualified;

        protected global::System.Web.UI.WebControls.Literal litTreeStatusOther;

        protected global::protectTreesV2._uc.dashboard.uc_treeStatusChart ucTreeStatusChart;

        protected global::protectTreesV2._uc.dashboard.uc_areaGroupPieChart ucAreaGroupPieChart;

        protected global::protectTreesV2._uc.dashboard.uc_speciesStatusChart ucSpeciesStatusChart;

        protected global::protectTreesV2._uc.dashboard.uc_healthCompletionChart ucHealthCompletionChart;

        protected global::protectTreesV2._uc.dashboard.uc_userLoginChart ucUserLoginChart;
    }
}
