//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2.pages
{


    public partial class map1
    {
        
        /// <summary>
        /// TreeDataJson 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField TreeDataJson;
    }
}
