//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2.backstage.tree
{


    public partial class detail
    {

        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        protected global::System.Web.UI.WebControls.HiddenField hfTreeID;

        protected global::System.Web.UI.WebControls.Label lblSystemTreeNo;

        protected global::System.Web.UI.WebControls.Label lblAgencyTreeNo;

        protected global::System.Web.UI.WebControls.Label lblJurisdiction;

        protected global::System.Web.UI.WebControls.Label lblCity;

        protected global::System.Web.UI.WebControls.Label lblArea;

        protected global::System.Web.UI.WebControls.Label lblSpecies;

        protected global::System.Web.UI.WebControls.Label lblStatus;

        protected global::System.Web.UI.WebControls.Label lblEditStatus;

        protected global::System.Web.UI.WebControls.Label lblSurveyDate;

        protected global::System.Web.UI.WebControls.Label lblAnnouncementDate;

        protected global::System.Web.UI.WebControls.Label lblManager;

        protected global::System.Web.UI.WebControls.Label lblManagerContact;

        protected global::System.Web.UI.WebControls.Label lblSite;

        protected global::System.Web.UI.WebControls.Label lblLandOwnership;

        protected global::System.Web.UI.WebControls.Label lblLandOwnershipNote;

        protected global::System.Web.UI.WebControls.Label lblTreeCount;

        protected global::System.Web.UI.WebControls.Label lblTreeHeight;

        protected global::System.Web.UI.WebControls.Label lblBreastHeightDiameter;

        protected global::System.Web.UI.WebControls.Label lblBreastHeightCircumference;

        protected global::System.Web.UI.WebControls.Label lblCanopyArea;

        protected global::System.Web.UI.WebControls.Label lblLatitude;

        protected global::System.Web.UI.WebControls.Label lblLongitude;

        protected global::System.Web.UI.WebControls.Label lblIsAnnounced;

        protected global::System.Web.UI.WebControls.Label lblRecognition;

        protected global::System.Web.UI.WebControls.Label lblRecognitionNote;

        protected global::System.Web.UI.WebControls.Label lblCulturalHistory;

        protected global::System.Web.UI.WebControls.Label lblHealth;

        protected global::System.Web.UI.WebControls.Label lblMemo;

        protected global::System.Web.UI.WebControls.Repeater rptPhotos;
    }
}
