//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//
//     變更這個檔案可能會導致不正確的行為，而且如果已重新產生
//     程式碼，則會遺失變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2.backstage.tree {
    
    
    public partial class edit {
        
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;
        
        protected global::System.Web.UI.WebControls.HiddenField hfTreeID;
        
        protected global::System.Web.UI.WebControls.Label lblSystemTreeNo;
        
        protected global::System.Web.UI.WebControls.TextBox txtAgencyTreeNo;
        
        protected global::System.Web.UI.WebControls.TextBox txtJurisdiction;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlCity;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlArea;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlSpecies;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlStatus;
        
        protected global::System.Web.UI.WebControls.TextBox txtSurveyDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtSurveyor;
        
        protected global::System.Web.UI.WebControls.TextBox txtAnnouncementDate;
        
        protected global::System.Web.UI.WebControls.TextBox txtTreeCount;

        protected global::System.Web.UI.WebControls.TextBox txtLatitude;

        protected global::System.Web.UI.WebControls.TextBox txtLongitude;

        protected global::System.Web.UI.WebControls.Button btnCoordinateTool;
        
        protected global::System.Web.UI.WebControls.TextBox txtSite;
        
        protected global::System.Web.UI.WebControls.TextBox txtManager;
        
        protected global::System.Web.UI.WebControls.TextBox txtManagerContact;
        
        protected global::System.Web.UI.WebControls.DropDownList ddlLandOwnership;
        
        protected global::System.Web.UI.WebControls.TextBox txtLandOwnershipNote;
        
        protected global::System.Web.UI.WebControls.TextBox txtFacility;
        
        protected global::System.Web.UI.WebControls.TextBox txtMemo;
        
        protected global::System.Web.UI.WebControls.TextBox txtTreeHeight;
        
        protected global::System.Web.UI.WebControls.TextBox txtBreastHeightDiameter;
        
        protected global::System.Web.UI.WebControls.TextBox txtBreastHeightCircumference;
        
        protected global::System.Web.UI.WebControls.TextBox txtCanopyArea;
        
        protected global::System.Web.UI.WebControls.CheckBoxList cblRecognition;
        
        protected global::System.Web.UI.WebControls.TextBox txtRecognitionNote;
        
        protected global::System.Web.UI.WebControls.TextBox txtCulturalHistory;
        
        protected global::System.Web.UI.WebControls.TextBox txtHealth;
        
        protected global::System.Web.UI.WebControls.Button btnSaveDraft;
        
        protected global::System.Web.UI.WebControls.Button btnSaveFinal;
        
        protected global::System.Web.UI.WebControls.Button btnCancel;
        
        protected global::System.Web.UI.WebControls.HyperLink lnkUploadPhotos;
    }
}
