//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace protectTreesV2._uc.patrol
{


    public partial class uc_patrolRecordModal
    {

        /// <summary>
        /// phEmpty 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phEmpty;

        /// <summary>
        /// phContent 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phContent;

        /// <summary>
        /// litRisk 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litRisk;

        /// <summary>
        /// litMemo 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litMemo;

        /// <summary>
        /// phPhotoEmpty 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.PlaceHolder phPhotoEmpty;

        /// <summary>
        /// rptPhotos 控制項。
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPhotos;
    }
}
